# Generated by Django 5.2.6 on 2026-01-28 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("description", models.TextField(help_text="Mission Briefing")),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("mission", "Mission (Course)"),
                            ("webinar", "Webinar (Live Ops)"),
                            ("hackathon", "Hackathon (Arena)"),
                        ],
                        default="mission",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("cadet", "Cadet (Beginner)"),
                            ("explorer", "Explorer (Intermediate)"),
                            ("astronaut", "Astronaut (Advanced)"),
                        ],
                        default="cadet",
                        max_length=20,
                    ),
                ),
                (
                    "instructor",
                    models.CharField(
                        help_text="Mission Commander / Speaker", max_length=100
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="e.g. '4 Weeks' or '2 Hours'", max_length=50
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_live", models.BooleanField(default=False)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "xp_reward",
                    models.IntegerField(default=100, help_text="XP for completion"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HackathonTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("project_link", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="hackathon_teams", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="programs.program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("video", "Video Transmission"),
                            ("text", "Mission Log"),
                            ("quiz", "Simulation Check"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Text content or Video URL")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "duration",
                    models.IntegerField(default=10, help_text="Estimated minutes"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="programs.module",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WebinarDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_link", models.URLField(blank=True)),
                ("recording_link", models.URLField(blank=True)),
                ("speakers", models.TextField(help_text="List of speakers/bios")),
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webinar_details",
                        to="programs.program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("completed", "Mission Accomplished"),
                            ("dropped", "Aborted"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, help_text="Percentage completed"),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "program")},
            },
        ),
    ]
