# Generated by Django 5.2.6 on 2026-01-27 16:52

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.AddField(
            model_name="event",
            name="agency",
            field=models.CharField(
                blank=True,
                help_text="e.g. SpaceX, NASA, ISRO",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="attending_events", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("astronomy", "Astronomical Event"),
                    ("launch", "Space Launch"),
                    ("industry", "Space Industry"),
                    ("community", "Community & Education"),
                    ("webinar", "Webinar/Workshop"),
                ],
                default="astronomy",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="date_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Event Start Time"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.DateTimeField(
                blank=True, help_text="Event End Time (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="equipment_needed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("naked_eye", "Naked Eye"),
                    ("binoculars", "Binoculars"),
                    ("telescope", "Telescope"),
                    ("none", "None Required"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="external_link",
            field=models.URLField(
                blank=True, help_text="Livestream or registration link"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="full_description",
            field=models.TextField(blank=True, help_text="Detailed overview"),
        ),
        migrations.AddField(
            model_name="event",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="is_live",
            field=models.BooleanField(
                default=False, help_text="Is this a live event (webinar/livestream)?"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="mission_name",
            field=models.CharField(
                blank=True, help_text="e.g. Starlink 12", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="region",
            field=models.CharField(
                default="Global",
                help_text="Visibility region or 'Global'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="rocket_name",
            field=models.CharField(
                blank=True, help_text="e.g. Falcon 9", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="scientific_explanation",
            field=models.TextField(
                blank=True, help_text="Simple scientific explanation"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="short_description",
            field=models.TextField(
                default="Upcoming event", help_text="1-2 lines for the card"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="timezone",
            field=models.CharField(
                default="UTC", help_text="e.g. UTC, Asia/Kolkata", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="viewing_guide",
            field=models.TextField(blank=True, help_text="Best time, direction, tips"),
        ),
    ]
