# Generated by Django 5.2.6 on 2026-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_remove_event_date_remove_event_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="launch_details",
            field=models.TextField(
                blank=True, help_text="Specific details about the launch sequence"
            ),
        ),
    ]
